SET search_path TO society_manager, public;
INSERT INTO m_module(module_code,module_name,parent_module_code,display_order) VALUES
('ADMINISTRATOR','Administrator',NULL,10),('BACK_OFFICE','Back Office',NULL,20),('BILLING_MANAGEMENT','Billing Management',NULL,30),('COLLECTION_MANAGEMENT','Collection Management',NULL,40),('CONNECTION_MANAGEMENT','Connection Management',NULL,50),('CRM','Customer Relationship Management',NULL,60),('APP_DASHBOARD','Dashboard',NULL,70),('DEVICE_AUTH','Device Authorization',NULL,80),('METER_MANAGEMENT','Meter Management System',NULL,90),('MIS','MIS',NULL,100),('RECOVERY_MANAGEMENT','Recovery Management [Discon & Recon]',NULL,120),('WATER_DISTRIBUTION','Water Distribution Management',NULL,130),('SOCIETY_ADMIN_EXTRA','Society Administration',NULL,140),('SECURITY_VISITOR','Security & Visitor Management',NULL,150),('PARKING_MANAGEMENT','Parking Management',NULL,160),('DOCUMENT_MANAGEMENT','Document Management',NULL,170),('NOTICE_COMMUNICATION','Notice & Communication',NULL,180),('REPORTING_ANALYTICS','Reports & Analytics',NULL,190),('AUDIT_GOVERNANCE','Audit & Governance',NULL,200),('MIGRATION_CONTROL','Migration Control',NULL,210),('SUBSCRIPTION_PLATFORM','Subscription & Platform Billing',NULL,220)
ON CONFLICT(module_code) DO UPDATE SET module_name=excluded.module_name,parent_module_code=excluded.parent_module_code,display_order=excluded.display_order;
INSERT INTO m_module(module_code,module_name,parent_module_code,display_order) VALUES
('ADM_CONTRACTOR','Add / Edit Contractor','ADMINISTRATOR',11),('ADM_EMPLOYEE','Add / Edit Employee','ADMINISTRATOR',12),('ADM_ROLE_MASTER','Role Master','ADMINISTRATOR',13),('ADM_ACCOUNTS','Manage Accounts','ADMINISTRATOR',14),('ADM_CUSTOMER_COUNTS','Customer Counts','ADMINISTRATOR',15),('ADM_SMS_CONFIG','SMS Configuration','ADMINISTRATOR',16),('ADM_MASTER_DATA','Master Data Entry','ADMINISTRATOR',17),('ADM_COLLECTION_CONFIG','Collection Configuration','ADMINISTRATOR',18),('ADM_SEND_SMS','Send SMS Manually','ADMINISTRATOR',20),
('BO_TICKET','Raise Ticket [IT Help Desk]','BACK_OFFICE',21),('BO_HELPDESK','IT Help Desk Dashboard','BACK_OFFICE',22),('BO_DOCUMENTS','Document Management System','BACK_OFFICE',23),('BO_SERVICE_ATTRIBUTES','Update Service Attributes','BACK_OFFICE',24),('BO_MASTER_MIGRATION','Master Data Migration','BACK_OFFICE',25),('BO_CONSUMER_MIGRATION','New Consumer Migration','BACK_OFFICE',26),
('BILL_RANGE','Billing Range Interface','BILLING_MANAGEMENT',31),('BILL_DUMMY_CYCLE','Dummy Cycle Bill Schedule','BILLING_MANAGEMENT',32),('BILL_ERROR_CORRECTION','Error Warning Correction','BILLING_MANAGEMENT',34),('BILL_COMPUTATION','Bill Computation','BILLING_MANAGEMENT',36),('BILL_DOWNLOAD','Download Bill','BILLING_MANAGEMENT',37),('BILL_REVERT','Revert Billing','BILLING_MANAGEMENT',38),('BILL_TRACKER','Billing Tracker Report','BILLING_MANAGEMENT',39),('BILL_ADJUSTMENT','Billing Adjustment','BILLING_MANAGEMENT',40),('BILL_TARIFF','Tariff Rate Details','BILLING_MANAGEMENT',41),('BILL_DUMMY','Dummy Billing','BILLING_MANAGEMENT',42),('BILL_ESTIMATE','Estimated Average Unit Interface','BILLING_MANAGEMENT',43),
('COL_ACCEPT','Accept Payment','COLLECTION_MANAGEMENT',51),('COL_SERVICE','Accept Services Payment','COLLECTION_MANAGEMENT',52),('COL_BANK','Add / Edit Bank Details','COLLECTION_MANAGEMENT',53),('COL_CENTER','Add / Edit Collection Center','COLLECTION_MANAGEMENT',54),('COL_CANCEL_SUMMARY','Cancel Receipt Summary','COLLECTION_MANAGEMENT',55),('COL_DAILY','Daily Collection Report','COLLECTION_MANAGEMENT',56),('COL_CHEQUE','Dishonored Cheque','COLLECTION_MANAGEMENT',57),('COL_COUNTER','Payment Collection Counter Report','COLLECTION_MANAGEMENT',58),('COL_RECON','Payment Reconciliation','COLLECTION_MANAGEMENT',59),('COL_RECEIPT_CANCEL','Receipt Cancellation','COLLECTION_MANAGEMENT',60),('COL_CANCEL_AUTH','Receipt Cancelled Authentication','COLLECTION_MANAGEMENT',61),
('CONN_APPLICATION','Connection Application','CONNECTION_MANAGEMENT',71),('CONN_SERVICE','Service / Connection Details','CONNECTION_MANAGEMENT',72),('CONN_TRANSFER','Connection Transfer','CONNECTION_MANAGEMENT',73),('CONN_DISCON_RECON','Disconnection / Reconnection','CONNECTION_MANAGEMENT',74),('CONN_HISTORY','Connection History','CONNECTION_MANAGEMENT',75),
('CRM_CUSTOMER_SEARCH','Customer Search','CRM',81),('CRM_CUSTOMER_360','Customer 360','CRM',82),('CRM_INTERACTION','Customer Interactions','CRM',83),('CRM_COMPLAINT','Complaints / Grievances','CRM',84),('CRM_SERVICE_REQUEST','Service Requests','CRM',85),
('DASH_BILLING','Billing','APP_DASHBOARD',91),('DASH_COLLECTION','Collection','APP_DASHBOARD',92),('DASH_CRM','CRM','APP_DASHBOARD',93),('DASH_RTS','RTS','APP_DASHBOARD',94),
('DEV_REGISTER','Device Registration','DEVICE_AUTH',101),('DEV_ASSIGN','Device Assignment','DEVICE_AUTH',102),('DEV_AUTH','Device Authentication','DEVICE_AUTH',103),('DEV_STATUS','Device Status','DEVICE_AUTH',104),
('MTR_MASTER','Meter Master','METER_MANAGEMENT',111),('MTR_ASSIGN','Meter Assignment','METER_MANAGEMENT',112),('MTR_REPLACEMENT','Meter Replacement','METER_MANAGEMENT',113),('MTR_TEST','Meter Testing','METER_MANAGEMENT',114),('MTR_HISTORY','Meter History','METER_MANAGEMENT',115),
('MIS_BILLING','Billing MIS','MIS',121),('MIS_COLLECTION','Collection MIS','MIS',122),('MIS_CONSUMER','Consumer MIS','MIS',123),('MIS_METER','Meter MIS','MIS',124),('MIS_EXCEPTION','Exception MIS','MIS',125),

('RECOVERY_DUE','Recovery Due List','RECOVERY_MANAGEMENT',141),('RECOVERY_DISCON','Disconnection','RECOVERY_MANAGEMENT',142),('RECOVERY_RECON','Reconnection','RECOVERY_MANAGEMENT',143),('RECOVERY_TRACKER','Recovery Tracker','RECOVERY_MANAGEMENT',144),
('WATER_CONSUMPTION','Water Consumption','WATER_DISTRIBUTION',151),('WATER_TANK','Tank / Supply Management','WATER_DISTRIBUTION',152),('WATER_SCHEDULE','Supply Schedule','WATER_DISTRIBUTION',153),('WATER_ZONE','Zone Management','WATER_DISTRIBUTION',154),
('SA_RATE','Rate / Tariff Configuration','SOCIETY_ADMIN_EXTRA',161),('SA_DPC','DPC / Interest Configuration','SOCIETY_ADMIN_EXTRA',162),('SA_REBATE','Rebate Configuration','SOCIETY_ADMIN_EXTRA',163),('SA_WAIVER','Waiver / Adjustment Rules','SOCIETY_ADMIN_EXTRA',164),('SA_TAX','Tax / GST Configuration','SOCIETY_ADMIN_EXTRA',165),('SA_EFFECTIVE','Effective Date / Versioning','SOCIETY_ADMIN_EXTRA',166),
('SEC_GATE','Gate Dashboard','SECURITY_VISITOR',171),('SEC_VISITOR','Visitor Entry / Exit','SECURITY_VISITOR',172),('SEC_APPROVAL','Resident Visitor Approval','SECURITY_VISITOR',173),('SEC_VEHICLE','Vehicle Entry / Exit','SECURITY_VISITOR',174),
('PARK_SLOT','Parking Slots','PARKING_MANAGEMENT',181),('PARK_ASSIGN','Parking Assignment','PARKING_MANAGEMENT',182),('PARK_VEHICLE','Vehicles','PARKING_MANAGEMENT',183),('PARK_CHARGE','Parking Charges','PARKING_MANAGEMENT',184),
('DOC_CUSTOMER','Customer Documents','DOCUMENT_MANAGEMENT',191),('DOC_SOCIETY','Society Documents','DOCUMENT_MANAGEMENT',192),('DOC_TEMPLATE','Templates','DOCUMENT_MANAGEMENT',193),
('NOTICE_CREATE','Notice Management','NOTICE_COMMUNICATION',201),('NOTICE_SMS','SMS / Email','NOTICE_COMMUNICATION',202),('NOTICE_PUSH','Notifications','NOTICE_COMMUNICATION',203),
('RPT_BILLING','Billing Reports','REPORTING_ANALYTICS',211),('RPT_COLLECTION','Collection Reports','REPORTING_ANALYTICS',212),('RPT_OUTSTANDING','Outstanding / Aging','REPORTING_ANALYTICS',213),('RPT_CONSUMER','Consumer Reports','REPORTING_ANALYTICS',214),('RPT_AUDIT','Audit Reports','REPORTING_ANALYTICS',215),
('AUDIT_LOG','Audit Trail','AUDIT_GOVERNANCE',221),('AUDIT_LOGIN','Login / Session Audit','AUDIT_GOVERNANCE',222),('AUDIT_APPROVAL','Approval History','AUDIT_GOVERNANCE',223),
('MIG_PREVIEW','Migration Preview','MIGRATION_CONTROL',231),('MIG_VALIDATE','Migration Validation','MIGRATION_CONTROL',232),('MIG_IMPORT','Import / Commit','MIGRATION_CONTROL',233),('MIG_ERRORS','Error Download','MIGRATION_CONTROL',234),('MIG_BATCH','Batch History / Rollback','MIGRATION_CONTROL',235),
('SUB_PLANS','Subscription Plans','SUBSCRIPTION_PLATFORM',241),('SUB_ACTIVE','Society Subscriptions','SUBSCRIPTION_PLATFORM',242),('SUB_PAYMENT','Subscription Payments','SUBSCRIPTION_PLATFORM',243),('SUB_RENEWAL','Renewal / Expiry','SUBSCRIPTION_PLATFORM',244)
ON CONFLICT(module_code) DO UPDATE SET module_name=excluded.module_name,parent_module_code=excluded.parent_module_code,display_order=excluded.display_order;
CREATE OR REPLACE FUNCTION fn_role_module_menu(p_role_code varchar)
RETURNS TABLE(module_code varchar,module_name varchar,parent_module_code varchar,display_order integer)
LANGUAGE sql AS $$
SELECT m.module_code,m.module_name,m.parent_module_code,m.display_order FROM m_module m WHERE m.is_active AND (
 p_role_code='SUPER_ADMIN'
 OR (p_role_code='SOCIETY_ADMIN' AND m.module_code NOT LIKE 'SUB_%')
 OR (p_role_code IN ('COLLECTOR','BILLING_ADMIN') AND m.parent_module_code IN ('BILLING_MANAGEMENT','COLLECTION_MANAGEMENT','CRM','APP_DASHBOARD'))
 OR (p_role_code='RESIDENT' AND m.module_code IN ('APP_DASHBOARD','DASH_BILLING','DASH_COLLECTION','DASH_CRM','CRM','CRM_CUSTOMER_360','CRM_COMPLAINT','RESIDENTS','PARKING_MANAGEMENT','PARK_SLOT','PARK_ASSIGN','PARK_VEHICLE','BILLING_MANAGEMENT','BILL_DOWNLOAD','COLLECTION_MANAGEMENT','COL_DAILY','DOCUMENT_MANAGEMENT','DOC_CUSTOMER','NOTICE_COMMUNICATION','NOTICE_CREATE','NOTICE_PUSH'))
) ORDER BY m.display_order,m.module_code;
$$;
CREATE OR REPLACE FUNCTION fn_module_catalog()
RETURNS TABLE(module_code varchar,module_name varchar,parent_module_code varchar,display_order integer)
LANGUAGE sql AS $$ SELECT module_code,module_name,parent_module_code,display_order FROM m_module WHERE is_active ORDER BY display_order,module_code; $$;
