using Npgsql;
using Society360.Data;
using Society360.Security;
namespace Society360.Modules.SocietyAdmin;
public static class OperationalConfigEndpoints
{
 public static void MapOperationalConfigEndpoints(this WebApplication app)
 {
  app.MapGet("/api/society-admin/config/charges",async(AuthService a,HttpContext h,CancellationToken c)=>await Query(a,h,c,"fn_society_charge_rules",9));
  app.MapGet("/api/society-admin/config/interest",async(AuthService a,HttpContext h,CancellationToken c)=>await Query(a,h,c,"fn_society_interest_rules",10));
  app.MapPost("/api/society-admin/config/charge",async(ChargeRuleRequest x,AuthService a,HttpContext h,CancellationToken c)=>await SaveCharge(x,a,h,c));
  app.MapPost("/api/society-admin/config/interest",async(InterestRuleRequest x,AuthService a,HttpContext h,CancellationToken c)=>await SaveInterest(x,a,h,c));
 }
 static async Task<IResult> Query(AuthService a,HttpContext h,CancellationToken c,string fn,int n){var s=await AuthGuard.Get(h,a,c);if(s is null)return Results.Unauthorized();if(s.RoleCode is not("SOCIETY_ADMIN" or "SUPER_ADMIN")||s.SocietyId is null)return Results.Forbid();await using var cn=new NpgsqlConnection(Environment.GetEnvironmentVariable("SOCIETY360_DB_CONNECTION"));await cn.OpenAsync(c);await using var cmd=new NpgsqlCommand($"select * from society_manager.{fn}(@society)",cn);cmd.Parameters.AddWithValue("society",s.SocietyId.Value);return Results.Ok(await Rows(cmd,n,c));}
 static async Task<IResult> SaveCharge(ChargeRuleRequest x,AuthService a,HttpContext h,CancellationToken c){var s=await AuthGuard.Get(h,a,c);if(s is null)return Results.Unauthorized();if(s.RoleCode is not("SOCIETY_ADMIN" or "SUPER_ADMIN")||s.SocietyId is null)return Results.Forbid();await using var cn=new NpgsqlConnection(Environment.GetEnvironmentVariable("SOCIETY360_DB_CONNECTION"));await cn.OpenAsync(c);await using var cmd=new NpgsqlCommand("select society_manager.fn_society_save_charge_rule(@society,@code,@plan,@method,@rate,@from,@to,@scope,@value,@user)",cn);cmd.Parameters.AddWithValue("society",s.SocietyId.Value);cmd.Parameters.AddWithValue("code",x.ChargeCode);cmd.Parameters.AddWithValue("plan",x.PlanName);cmd.Parameters.AddWithValue("method",x.Method);cmd.Parameters.AddWithValue("rate",x.Rate);cmd.Parameters.AddWithValue("from",x.EffectiveFrom);cmd.Parameters.AddWithValue("to",(object?)x.EffectiveTo??DBNull.Value);cmd.Parameters.AddWithValue("scope",x.ScopeType);cmd.Parameters.AddWithValue("value",(object?)x.ScopeValue??DBNull.Value);cmd.Parameters.AddWithValue("user",s.UserId);return Results.Ok(new{success=true,id=await cmd.ExecuteScalarAsync(c)});}
 static async Task<IResult> SaveInterest(InterestRuleRequest x,AuthService a,HttpContext h,CancellationToken c){var s=await AuthGuard.Get(h,a,c);if(s is null)return Results.Unauthorized();if(s.RoleCode is not("SOCIETY_ADMIN" or "SUPER_ADMIN")||s.SocietyId is null)return Results.Forbid();await using var cn=new NpgsqlConnection(Environment.GetEnvironmentVariable("SOCIETY360_DB_CONNECTION"));await cn.OpenAsync(c);await using var cmd=new NpgsqlCommand("select society_manager.fn_society_save_interest_rule(@society,@name,@type,@rate,@frequency,@compound,@grace,@cap,@from,@to,@user)",cn);cmd.Parameters.AddWithValue("society",s.SocietyId.Value);cmd.Parameters.AddWithValue("name",x.RuleName);cmd.Parameters.AddWithValue("type",x.CalculationType);cmd.Parameters.AddWithValue("rate",x.Rate);cmd.Parameters.AddWithValue("frequency",x.Frequency);cmd.Parameters.AddWithValue("compound",x.SimpleOrCompound);cmd.Parameters.AddWithValue("grace",x.GraceDays);cmd.Parameters.AddWithValue("cap",(object?)x.CapAmount??DBNull.Value);cmd.Parameters.AddWithValue("from",x.EffectiveFrom);cmd.Parameters.AddWithValue("to",(object?)x.EffectiveTo??DBNull.Value);cmd.Parameters.AddWithValue("user",s.UserId);return Results.Ok(new{success=true,id=await cmd.ExecuteScalarAsync(c)});}
 static async Task<List<Dictionary<string,object?>>> Rows(NpgsqlCommand cmd,int n,CancellationToken c){await using var r=await cmd.ExecuteReaderAsync(c);var rows=new List<Dictionary<string,object?>>();while(await r.ReadAsync(c)){var row=new Dictionary<string,object?>();for(var i=0;i<n;i++)row[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);rows.Add(row);}return rows;}
}
public sealed record ChargeRuleRequest(string ChargeCode,string PlanName,string Method,decimal Rate,DateOnly EffectiveFrom,DateOnly? EffectiveTo,string ScopeType,string? ScopeValue);
public sealed record InterestRuleRequest(string RuleName,string CalculationType,decimal Rate,string Frequency,string SimpleOrCompound,int GraceDays,decimal? CapAmount,DateOnly EffectiveFrom,DateOnly? EffectiveTo);